### ISSUE TITLE
Ubuntu 14 install fails with compiler error

### ISSUE THREAD

**Issue by duel007** [salsoftware/sal#71]
Working on a test install of Sal on Ubuntu, and following along the guide I get to here and end with warnings and a compiler error. Verified issue on both my testbed and a fresh install of 14.04 LTS.

```
 (sal_env)saluser@netsus:/usr/local/sal_env$ pip install -r sal/setup/requirement s.txt
Downloading/unpacking Django==1.5.3 (from -r sal/setup/requirements.txt (line 1) )
  Downloading Django-1.5.3.tar.gz (8.0MB): 8.0MB downloaded
  Running setup.py egg_info for package Django

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Downloading/unpacking South==0.8.2 (from -r sal/setup/requirements.txt (line 2))
  Downloading South-0.8.2.tar.gz (95kB): 95kB downloaded
  Running setup.py egg_info for package South

Downloading/unpacking Yapsy==1.10.223 (from -r sal/setup/requirements.txt (line 3))
  Downloading Yapsy-1.10.223.tar.gz (146kB): 146kB downloaded
  Running setup.py egg_info for package Yapsy

    no previously-included directories found matching 'src2/package/doc/_build'
    no previously-included directories found matching 'src3/package/doc/_build'
Downloading/unpacking django-bootstrap3==4.11.0 (from -r sal/setup/requirements.txt (line 4))
  Downloading django-bootstrap3-4.11.0.tar.gz
  Running setup.py egg_info for package django-bootstrap3

    warning: no files found matching '*.png' under directory 'bootstrap3'
    warning: no files found matching '*.gif' under directory 'bootstrap3'
    warning: no files found matching '*js' under directory 'bootstrap3'
    warning: no files found matching '*jpg' under directory 'bootstrap3'
    warning: no files found matching '*jpeg' under directory 'bootstrap3'
    warning: no files found matching '*svg' under directory 'bootstrap3'
    warning: no files found matching '*.png' under directory 'demo'
    warning: no files found matching '*.gif' under directory 'demo'
    warning: no files found matching '*js' under directory 'demo'
    warning: no files found matching '*jpg' under directory 'demo'
    warning: no files found matching '*jpeg' under directory 'demo'
    warning: no files found matching '*svg' under directory 'demo'
Downloading/unpacking docutils==0.11 (from -r sal/setup/requirements.txt (line 5))
  Downloading docutils-0.11.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py egg_info for package docutils

    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking requests==2.5.0 (from -r sal/setup/requirements.txt (line 6))
  Downloading requests-2.5.0.tar.gz (443kB): 443kB downloaded
  Running setup.py egg_info for package requests

Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/lib/python2.7 (from -r sal/setup/requirements.txt (line 7))
Downloading/unpacking python-dateutil==2.2 (from -r sal/setup/requirements.txt (line 8))
  Downloading python-dateutil-2.2.tar.gz (259kB): 259kB downloaded
  Running setup.py egg_info for package python-dateutil

Downloading/unpacking pytz==2014.3 (from -r sal/setup/requirements.txt (line 9))
  Downloading pytz-2014.3.tar.bz2 (158kB): 158kB downloaded
  Running setup.py egg_info for package pytz

Downloading/unpacking pyOpenSSL==0.14 (from -r sal/setup/requirements.txt (line 10))
  Downloading pyOpenSSL-0.14.tar.gz (128kB): 128kB downloaded
  Running setup.py egg_info for package pyOpenSSL

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
Downloading/unpacking ndg-httpsclient==0.3.2 (from -r sal/setup/requirements.txt (line 11))
  Downloading ndg_httpsclient-0.3.2.tar.gz
  Running setup.py egg_info for package ndg-httpsclient

Downloading/unpacking pyasn1==0.1.7 (from -r sal/setup/requirements.txt (line 12))
  Downloading pyasn1-0.1.7.tar.gz (68kB): 68kB downloaded
  Running setup.py egg_info for package pyasn1

Downloading/unpacking urllib3==1.10 (from -r sal/setup/requirements.txt (line 13))
  Downloading urllib3-1.10.tar.gz (128kB): 128kB downloaded
  Running setup.py egg_info for package urllib3

    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking six (from python-dateutil==2.2->-r sal/setup/requirements.txt (line 8))
  Downloading six-1.9.0.tar.gz
  Running setup.py egg_info for package six

    no previously-included directories found matching 'documentation/_build'
Downloading/unpacking cryptography>=0.2.1 (from pyOpenSSL==0.14->-r sal/setup/requirements.txt (line 10))
  Downloading cryptography-0.9.1.tar.gz (302kB): 302kB downloaded
  Running setup.py egg_info for package cryptography

    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking idna (from cryptography>=0.2.1->pyOpenSSL==0.14->-r sal/setup/requirements.txt (line 10))
  Downloading idna-2.0.tar.gz (135kB): 135kB downloaded
  Running setup.py egg_info for package idna

    warning: no previously-included files matching '*.pyc' found under directory 'tools'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from cryptography>=0.2.1->pyOpenSSL==0.14->-r sal/setup/requirements.txt (line 10))
Downloading/unpacking enum34 (from cryptography>=0.2.1->pyOpenSSL==0.14->-r sal/setup/requirements.txt (line 10))
  Downloading enum34-1.0.4.tar.gz
  Running setup.py egg_info for package enum34

Downloading/unpacking ipaddress (from cryptography>=0.2.1->pyOpenSSL==0.14->-r sal/setup/requirements.txt (line 10))
  Downloading ipaddress-1.0.7.tar.gz
  Running setup.py egg_info for package ipaddress

Downloading/unpacking cffi>=0.8 (from cryptography>=0.2.1->pyOpenSSL==0.14->-r sal/setup/requirements.txt (line 10))
  Downloading cffi-1.1.1.tar.gz (326kB): 326kB downloaded
  Running setup.py egg_info for package cffi
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory

        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.
        (If they are about -mno-fused-madd and you are on OS/X 10.8,
        see http://stackoverflow.com/questions/22313407/ .)
    Complete output from command python setup.py egg_info:
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory

unable to execute 'x86_64-linux-gnu-gcc': No such file or directory



    No working compiler found, or bogus compiler options

    passed to the compiler from Python's distutils module.

    See the error messages above.

    (If they are about -mno-fused-madd and you are on OS/X 10.8,

    see http://stackoverflow.com/questions/22313407/ .)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /usr/local/sal_env/build/cffi
Traceback (most recent call last):
  File "/usr/local/sal_env/bin/pip", line 9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/pip/basecommand.py", line 171, in main
    log_fp = open_logfile(log_fn, 'w')
  File "/usr/local/sal_env/local/lib/python2.7/site-packages/pip/basecommand.py", line 200, in open_logfile
    os.makedirs(dirname)
  File "/usr/local/sal_env/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/saluser/.pip'
```

**Comment by chasetb** [comment]
Looks like saluser doesn't have permissions to it's home folder. Run the following as root and then try again: 
``chown -R saluser /home/saluser``

**Comment by duel007** [comment]
Closing this, that did resolve the issue but I ended up using docker instead since that's more officially supported.
